const questions=window.OPP_QUESTIONS||[];
const categories={
commercial_clarity:'Commercial clarity',revenue_resilience:'Revenue resilience',proposition:'Proposition & productisation',icp:'ICP & market focus',evidence:'Win/loss evidence',pipeline_economics:'Pipeline economics',pipeline_discipline:'Pipeline discipline',qualification:'Qualification',demand:'Demand generation',proof:'Proof & collateral',relationships:'Relationships & referrals',growth_ops:'Growth operations',sales_capability:'Sales capability',ownership:'Ownership & culture',market_readiness:'Market readiness',priorities:'Priorities'
};
const seedClients=[
{id:'before-work',company:'BEFORE:WORK',contact:'James',accent:'#de5c43'},
{id:'pattrn',company:'Pattrn Studios',contact:'',accent:'#5f6b57'},
{id:'social-element',company:'The Social Element',contact:'',accent:'#745ca8'}
];
function getClients(){const saved=JSON.parse(localStorage.getItem('opp-map:clients')||'null');if(saved)return saved;localStorage.setItem('opp-map:clients',JSON.stringify(seedClients));return seedClients}
function saveClients(clients){localStorage.setItem('opp-map:clients',JSON.stringify(clients))}
function getMeta(id){return JSON.parse(localStorage.getItem(`opp-map:${id}:meta`)||'{}')}
function getAnswers(id){return JSON.parse(localStorage.getItem(`opp-map:${id}:answers`)||'{}')}
function scoreCategory(category,answers){const relevant=questions.filter(q=>q.category===category&&q.type==='options');let earned=0,max=0,count=0;relevant.forEach(q=>{const ans=answers[q.id];if(!ans)return;const opt=q.options.find(o=>(typeof o==='string'?o:o.label)===ans);if(!opt||typeof opt==='string'||typeof opt.score!=='number')return;earned+=opt.score;max+=4;count++});if(!count)return null;return Math.round((earned/max)*100)}
function statusFromScore(score){if(score===null)return 'Not scored';if(score>=75)return 'Strong';if(score>=55)return 'Opportunity';if(score>=35)return 'Needs attention';return 'Critical'}
function findingFromCategory(key,score){const status=statusFromScore(score);const templates={
commercial_clarity:'Growth ambition needs to connect more clearly to revenue mechanics and delivery capacity.',revenue_resilience:'Client concentration may be creating avoidable commercial exposure.',proposition:'The offer needs sharper packaging so prospects can understand what to buy and why it matters.',icp:'Targeting needs tighter prioritisation around the clients most likely to buy.',pipeline_economics:'The revenue target has not yet been translated into reliable funnel maths.',pipeline_discipline:'Pipeline is not yet operating as a consistently managed commercial system.',qualification:'Opportunity selection is likely contributing to wasted sales effort and weaker conversion.',demand:'Marketing and new-business activity need a clearer connection to qualified conversations.',proof:'Commercial proof could work harder to support the proposition and reduce buyer uncertainty.',relationships:'Warm relationships appear under-systemised as a route to growth.',growth_ops:'Systems exist primarily as tools rather than a joined-up operating process.',sales_capability:'The sales journey contains capability gaps that may need coaching or clearer playbooks.',ownership:'Growth ownership and protected time are not yet strong enough to sustain momentum.'};
return {status,title:categories[key],body:templates[key]||'This area warrants closer consultant review.'}}
function renderClients(){const clients=getClients();const list=document.getElementById('clientList');list.innerHTML=clients.map(c=>{const meta=getMeta(c.id);const pct=meta.totalQuestions?Math.round(((meta.answerCount||0)/meta.totalQuestions)*100):0;const state=meta.complete?'Review ready':pct?`${pct}% complete`:'Not started';return `<button class="client admin-client" data-id="${c.id}"><div><strong>${escapeHtml(c.company)}</strong><br><small>${escapeHtml(c.contact||'No contact set')} · ${state}</small></div><span class="status">${pct}%</span></button>`}).join('');document.querySelectorAll('.admin-client').forEach(btn=>btn.onclick=()=>selectClient(btn.dataset.id));}
function selectClient(id){const client=getClients().find(c=>c.id===id);if(!client)return;document.getElementById('selectedClient').textContent=client.company;const answers=getAnswers(id),meta=getMeta(id);document.getElementById('metricComplete').textContent=meta.totalQuestions?`${Math.round(((meta.answerCount||0)/meta.totalQuestions)*100)}%`:'0%';const scored=Object.keys(categories).map(k=>({key:k,score:scoreCategory(k,answers)})).filter(x=>x.score!==null).sort((a,b)=>a.score-b.score);document.getElementById('metricSignals').textContent=scored.length;document.getElementById('metricEvidence').textContent=Object.keys(answers).length;const findings=document.getElementById('findings');if(!scored.length){findings.innerHTML='<div class="empty-state">No scored responses yet. Open the client link and complete a few diagnostic questions to see live findings appear here.</div>'}else{findings.innerHTML=scored.slice(0,5).map(x=>{const f=findingFromCategory(x.key,x.score);return `<div class="finding"><span class="status status-${slug(f.status)}">${f.status}</span><h3>${f.title}</h3><p>${f.body}</p><div class="score-line"><span>Diagnostic signal</span><strong>${x.score}/100</strong></div><div class="finding-actions"><button class="primary tiny">Accept</button><button class="secondary tiny">Edit</button><button class="secondary tiny">Dismiss</button></div></div>`}).join('')}
const base=`${location.origin}${location.pathname.replace('admin.html','')}`;document.getElementById('clientLink').value=`${base}?client=${encodeURIComponent(client.id)}&company=${encodeURIComponent(client.company)}&contact=${encodeURIComponent(client.contact||'')}&accent=${encodeURIComponent(client.accent||'#17263b')}`;document.getElementById('openClient').href=document.getElementById('clientLink').value;document.getElementById('answerDump').innerHTML=questions.filter(q=>answers[q.id]!==undefined).map(q=>`<div class="answer-row"><div><span>${q.id} · ${escapeHtml(q.chapter)}</span><strong>${escapeHtml(q.title)}</strong></div><p>${escapeHtml(Array.isArray(answers[q.id])?answers[q.id].join(', '):answers[q.id])}</p></div>`).join('')||'<div class="empty-state">No responses yet.</div>';
}
function createClient(){const company=document.getElementById('newCompany').value.trim();if(!company)return;const contact=document.getElementById('newContact').value.trim();const accent=document.getElementById('newAccent').value||'#17263b';const id=(company.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')||`client-${Date.now()}`);const clients=getClients();if(!clients.some(c=>c.id===id))clients.unshift({id,company,contact,accent});saveClients(clients);document.getElementById('createPanel').classList.remove('open');renderClients();selectClient(id)}
function slug(v){return v.toLowerCase().replace(/\s+/g,'-')}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.getElementById('showCreate').onclick=()=>document.getElementById('createPanel').classList.toggle('open');document.getElementById('createClient').onclick=createClient;document.getElementById('copyLink').onclick=async()=>{const input=document.getElementById('clientLink');await navigator.clipboard.writeText(input.value);document.getElementById('copyLink').textContent='Copied';setTimeout(()=>document.getElementById('copyLink').textContent='Copy link',1200)};document.getElementById('toggleAnswers').onclick=()=>document.getElementById('answersPanel').classList.toggle('open');renderClients();selectClient(getClients()[0].id);
