import { supabase } from './supabase-config.js';

const authPanel=document.getElementById('authPanel'),workspace=document.getElementById('workspace'),authMessage=document.getElementById('authMessage'),clientList=document.getElementById('clientList'),createForm=document.getElementById('createClientForm'),generatedLink=document.getElementById('generatedLink'),signOutBtn=document.getElementById('signOutBtn');
const msg=(t)=>authMessage.textContent=t;
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function hash(v){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function token(){const b=crypto.getRandomValues(new Uint8Array(32));return btoa(String.fromCharCode(...b)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
async function state(){const {data:{session}}=await supabase.auth.getSession();if(!session)return {session:null,profile:null};const {data:profile}=await supabase.from('profiles').select('id,display_name,role').eq('id',session.user.id).maybeSingle();return {session,profile}}
async function refresh(){const {session,profile}=await state();signOutBtn.hidden=!session;if(!session){authPanel.hidden=false;workspace.hidden=true;return}if(!profile||!['consultant','admin'].includes(profile.role)){authPanel.hidden=false;workspace.hidden=true;msg('Signed in. This account is waiting for consultant access.');return}authPanel.hidden=true;workspace.hidden=false;document.getElementById('signedInAs').textContent=profile.display_name||session.user.email;await load()}
async function signup(){const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value;if(!email||password.length<8)return msg('Use a valid email and a password of at least 8 characters.');msg('Creating account…');const {error}=await supabase.auth.signUp({email,password});msg(error?error.message:'Account created. Confirm your email if asked, then sign in.')}
async function signin(){const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value;msg('Signing in…');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)return msg(error.message);await refresh()}
async function load(){const {data,error}=await supabase.from('engagements').select('id,status,created_at,client:clients(name),contact:client_contacts(name),responses(id,status,response_answers(id))').order('created_at',{ascending:false});if(error){clientList.innerHTML=`<p>${esc(error.message)}</p>`;return}clientList.innerHTML=(data||[]).map(r=>{const resp=r.responses?.[0],n=resp?.response_answers?.length||0;return `<div class="client"><div><strong>${esc(r.client?.name||'Client')}</strong><br><small>${esc(r.contact?.name||'')} · ${n} answers</small></div><span class="status">${esc(resp?.status||r.status)}</span></div>`}).join('')||'<p class="muted">No client diagnostics yet.</p>'}
async function createDiagnostic(e){e.preventDefault();const submit=createForm.querySelector('button[type="submit"]');submit.disabled=true;submit.textContent='Creating…';try{const {session}=await state();if(!session)throw new Error('Please sign in again.');const name=document.getElementById('clientName').value.trim(),contactName=document.getElementById('contactName').value.trim(),contactEmail=document.getElementById('contactEmail').value.trim(),website=document.getElementById('clientWebsite').value.trim(),primaryColor=document.getElementById('primaryColor').value;if(!name||!contactName)throw new Error('Client and contact name are required.');const {data:qv,error:qerr}=await supabase.from('questionnaire_versions').select('id').eq('name','Growth Opportunity Mapping').eq('status','published').order('version',{ascending:false}).limit(1).single();if(qerr)throw qerr;const {data:client,error:cerr}=await supabase.from('clients').insert({name,website_url:website||null,created_by:session.user.id}).select('id').single();if(cerr)throw cerr;const {data:contact,error:coerr}=await supabase.from('client_contacts').insert({client_id:client.id,name:contactName,email:contactEmail||null,is_primary:true}).select('id').single();if(coerr)throw coerr;await supabase.from('client_brand_profiles').insert({client_id:client.id,source_url:website||null,primary_color:primaryColor,background_color:'#f3f0e8',approved_at:new Date().toISOString(),approved_by:session.user.id});const raw=token();const {error:eerr}=await supabase.from('engagements').insert({client_id:client.id,questionnaire_version_id:qv.id,primary_contact_id:contact.id,mode:'self_complete',status:'sent',public_token_hash:await hash(raw),created_by:session.user.id});if(eerr)throw eerr;const url=new URL('./',location.href);url.searchParams.set('token',raw);generatedLink.hidden=false;generatedLink.innerHTML=`<span>Client diagnostic link</span><div class="generated-row"><input id="shareUrl" value="${url.href}" readonly><button class="secondary tiny" id="copyLinkBtn" type="button">Copy</button></div>`;document.getElementById('copyLinkBtn').onclick=async()=>{await navigator.clipboard.writeText(url.href);document.getElementById('copyLinkBtn').textContent='Copied'};createForm.reset();document.getElementById('primaryColor').value='#17263b';await load()}catch(err){alert(err.message||'Could not create diagnostic')}finally{submit.disabled=false;submit.textContent='Create client diagnostic'}}
document.getElementById('signUpBtn').onclick=signup;document.getElementById('signInBtn').onclick=signin;signOutBtn.onclick=async()=>{await supabase.auth.signOut();location.reload()};createForm.addEventListener('submit',createDiagnostic);supabase.auth.onAuthStateChange(()=>setTimeout(refresh,0));refresh();
