const questions=[
{chapter:'Your ambition',title:'What would make the next 12 months feel commercially successful?',help:'Think beyond a topline revenue number. Client mix, margin, independence, reputation and pace all count.',type:'textarea'},
{chapter:'Your ambition',title:'How much of your growth needs to come from new clients?',help:'A rough split is enough.',type:'options',options:['Mostly existing clients','About 50/50','Mostly new clients','I’m not sure yet']},
{chapter:'What you sell',title:'How clearly defined are your current offers?',help:'Choose the answer that feels most accurate today.',type:'options',options:['Very clearly defined','Mostly clear','Somewhat vague','Highly bespoke / open-ended']},
{chapter:'What you sell',title:'Why do clients choose you rather than another agency or supplier?',help:'What do you believe genuinely tips the decision in your favour?',type:'textarea'},
{chapter:'Who buys it',title:'What types of organisations are your best clients today?',help:'Describe the patterns you see across your strongest relationships.',type:'textarea'},
{chapter:'Who buys it',title:'When is a prospect most likely to need you?',help:'Think about triggers such as launches, rebrands, leadership changes or transformation programmes.',type:'textarea'},
{chapter:'How opportunities happen',title:'Where do new-business opportunities live today?',help:'Choose the closest answer.',type:'options',options:['A CRM','A spreadsheet / Notion','Mostly inboxes and people’s heads','Honestly, everywhere']},
{chapter:'How opportunities happen',title:'How consistently are active opportunities followed up?',help:'Be candid. This is about what happens in practice.',type:'options',options:['Always','Usually','Sometimes','Rarely / no defined process']},
{chapter:'The growth machine',title:'How well is your CRM or pipeline system actually used?',help:'If you don’t have one, choose the last option.',type:'options',options:['Very consistently','Reasonably well','Patchily','We don’t really have one']},
{chapter:'The growth machine',title:'Which part of your process feels unnecessarily manual?',help:'Anything repetitive, hard to track, or dependent on someone remembering.',type:'textarea'},
{chapter:'Ownership',title:'What most often gets in the way of consistent new-business activity?',help:'Pick the biggest blocker.',type:'options',options:['Client delivery takes over','No clear owner or rhythm','We’re unsure who to target','We’re unsure what to say']},
{chapter:'Priorities',title:'If we fixed one thing in the next 90 days, what would you want it to be?',help:'The answer can be strategic, operational or behavioural.',type:'textarea'}
];
let index=0;const answers=JSON.parse(localStorage.getItem('opp-map-answers')||'{}');
const welcome=document.getElementById('welcome'),questionnaire=document.getElementById('questionnaire'),complete=document.getElementById('complete'),host=document.getElementById('questionHost');
function show(el){[welcome,questionnaire,complete].forEach(x=>x.classList.remove('active'));el.classList.add('active')}
function render(){const q=questions[index];document.getElementById('chapterName').textContent=q.chapter;document.getElementById('progress').style.width=`${((index+1)/questions.length)*100}%`;let body=`<h2 class="question-title">${q.title}</h2><p class="question-help">${q.help||''}</p>`;if(q.type==='textarea'){body+=`<textarea class="textarea" id="answerInput" placeholder="Type your answer here…">${answers[index]||''}</textarea>`}else{body+=`<div class="option-grid">${q.options.map(o=>`<button class="option ${answers[index]===o?'selected':''}" data-value="${o.replace(/"/g,'&quot;')}">${o}</button>`).join('')}</div>`}host.innerHTML=body;document.getElementById('backBtn').style.visibility=index===0?'hidden':'visible';document.querySelectorAll('.option').forEach(btn=>btn.onclick=()=>{answers[index]=btn.dataset.value;save();render()});}
function save(){localStorage.setItem('opp-map-answers',JSON.stringify(answers))}
document.getElementById('startBtn').onclick=()=>{show(questionnaire);render()};document.getElementById('backBtn').onclick=()=>{capture();if(index>0){index--;render()}};document.getElementById('nextBtn').onclick=()=>{capture();if(index<questions.length-1){index++;render()}else{localStorage.setItem('opp-map-complete','true');show(complete)}};document.getElementById('restartBtn').onclick=()=>{index=0;show(welcome)};
function capture(){const input=document.getElementById('answerInput');if(input){answers[index]=input.value.trim();save()}}
